version: '3.3'
services:
  backend:
    container_name: backend_simple_solutions
    image: "simplesolution:latest"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod
    volumes:
      - .:/app
    ports:
      - "8050:8050"
    expose:
      - "8050"
    command: sh -c "poetry run python manage.py makemigrations &&
      poetry run python manage.py migrate &&
      poetry run python manage.py create_items &&
      poetry run gunicorn --workers=4 --reload --max-requests=1000 SimpleSolutionsTestTask.wsgi -b 0.0.0.0:8050"

  nginx:
    container_name: nginx_simple_solutions
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "82:82"
      - "443:443"
    volumes:
      - ./nginx/prod/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - backend
    depends_on:
      - backend
