version: '3.3'
services:
  backend:
    container_name: backend_simple_solutions
    image: "simplesolution:latest"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    volumes:
      - .:/app
    ports:
      - "8050:8050"
    expose:
      - "8050"
    command: sh -c "poetry run python manage.py makemigrations &&
      poetry run python manage.py migrate &&
      poetry run python manage.py create_items &&
      poetry run python manage.py runserver localhost:8000"

  nginx:
    container_name: nginx_simple_solutions
    working_dir: /app
    image: nginx:stable-alpine
    restart: always
    ports:
      - "8080:80"
      - "4443:443"
    volumes:
      - ./nginx/dev/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - backend
    depends_on:
      - backend
